#!/usr/bin/env python
# coding=utf8

import urllib   #urllib模块可以从指定的URL地址获取想要的网页数据
import urllib2  #urllib2这个组件来抓取网页，一个获取URLs的组件
import cookielib  #提供可存储cookie的对象，以便于与urllib2模块配合使用来访问Internet资源
import base64    #用来作base64编码解码
import re       #正则表达式
import json     #数据交换格式
import rsa     #rsa加密算法
import binascii   #二进制和ASCII互转以及其他进制转换

class WeiboLogin:

	username = ''
	password = ''
	serverUrl = ''
	loginUrl = 'http://login.sina.com.cn/sso/login.php?client=ssologin.js(v1.4.11)'

	postData = {
		'entry': 'weibo',
		'gateway': '1',
		'from': '',
		'savestate': '7',
		'userticket': '1',
		'pagerefer': 'http://weibo.com/a/download',
		'vsnf': '1',
		'su': '',
		'service': 'miniblog',
		'servertime': '',
		'nonce': '',
		'pwencode': 'rsa2',
		'rsakv': '',
		'sp': '',
		'encoding': 'UTF-8',
		'prelt': '60',
		'url': 'http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOController.feedBackUrlCallBack',
		'returntype': 'META'
	}

	def __init__(self, username, password):
		self.username = username
		self.password = password
		self.serverUrl = 'http://login.sina.com.cn/sso/prelogin.php?entry=sso&callback=sinaSSOController.preloginCallBack&su=%s&rsakt=mod&client=ssologin.js(v1.4.11)' % username
		
		cookiejar = cookielib.LWPCookieJar()  #获取一个cookiejar实例
		cookie_support = urllib2.HTTPCookieProcessor(cookiejar)   #获取一个HTTPCookieProcessor Handler对象
		opener = urllib2.build_opener(cookie_support, urllib2.HTTPHandler(debuglevel=1))
		urllib2.install_opener(opener)   #设置opener作为默认的全局handler


	def login(self):
		servertime, nonce, pubkey, rsakv = self.getServerTime()

		self.postData['servertime'] = servertime
		self.postData['nonce'] = nonce
		self.postData['rsakv'] = rsakv
		self.postData['su'] = self.getSu()
		self.postData['sp'] = self.getSp(servertime, nonce, pubkey)
		
		text = self.getUrl(self.loginUrl, self.postData, 'POST')

		p = re.compile('location\.replace\(\"(.*)\"\)')  #正则表达式编译成一个正则表达式对象
		
		try:
			loginUrl = p.search(text).group(1)
			self.getUrl(loginUrl)
			print "Login success!"
			return True
		except:
			print 'Login error!'
			return False
